### ISSUE TITLE
Not super clear why `sel!` and `isel!` modify the `JuxtArray`?

### ISSUE THREAD

**Issue by ali-ramadhan** [beta-effect/juxta.jl#7]
I'm probably just misunderstanding but I thought when you select part of a `JuxtArray`, either through physical slicing or index-based slicing, that you would get back a new `JuxtArray` containing just the selected portion, which shouldn't modify the existing `JuxtArray`.

But it seems that these functions actually modify the existing `JuxtArray` and overwrite `ja.array`? Don't you lose data this way?

**Comment by beta-effect** [comment]
We save memory at the expense of losing data. My main concern was preserving memory because these arrays often get very big and we don't yet have xarray's chunking and lazy evaluation. But I agree that if we implement slicing such that it creates new arrays, the struct could be immutable and allow some compile-time optimizations. Let's cross the memory bridge when we get to it. 

Closing this issue to continue discussion in #3.
